Repository kubescape/kubevuln, pull requests merged in 2023-10, with the labels that each got.

#171 add top level permissions: read-all for openssf
  .github/workflows/pr-created.yaml
  .github/workflows/pr-merged.yaml
Labels: enhancement

#172 Create scorecard.yml
  .github/workflows/scorecard.yml
Labels: enhancement

#173 OpenSSF Scorecard
  README.md
Labels: documentation

#177 Project management parts added
  MAINTAINERS.md
  README.md
  SECURITY-INSIGHTS.yml
  SECURITY.md
Labels: documentation

#154 Support backend access key
  adapters/v1/backend.go
  adapters/v1/backend_test.go
  adapters/v1/backend_utils.go
  cmd/http/main.go
  go.mod
  go.sum
Labels: enhancement, release

#180 fix permissions
  .github/workflows/pr-merged.yaml
Labels: enhancement, release

#181 trigger build
  cmd/http/main.go
Labels: release

#179 Kubevuln support for VEX document creation
  cmd/http/main.go
  cmd/http/main_test.go
  config/config.go
  core/ports/repositories.go
  core/services/scan.go
  core/services/scan_test.go
  go.mod
  go.sum
  repositories/apiserver.go
  repositories/apiserver_test.go
  repositories/broken.go
  repositories/memory.go
  repositories/testdata/nginx-cve-filtered-2.json
  repositories/testdata/nginx-cve-filtered.json
  repositories/testdata/nginx-cve.json
Labels: enhancement, release

#182 get default ns from env var
  cmd/http/main.go
  config/config.go
  go.mod
  go.sum
Labels: enhancement, release

#183 removed failed test
  repositories/apiserver_test.go
Labels: release, Tests

#184 Update backend pkg
  go.mod
  go.sum
Labels: enhancement
