Repository kubescape/kubevuln, pull requests merged in 2024-01, with the labels that each got.

#196 Merge branch 'feat-store-syft-sboms'
  .github/workflows/pr-created.yaml
  .github/workflows/pr-merged.yaml
  Makefile
  adapters/mocksbom.go
  adapters/v1/backend.go
  adapters/v1/backend_test.go
  adapters/v1/domain_to_armo.go
  adapters/v1/domain_to_armo_test.go
  adapters/v1/domain_to_syft.go
  adapters/v1/domain_to_syft_test.go
  adapters/v1/grype.go
  adapters/v1/grype_test.go
  adapters/v1/syft.go
  adapters/v1/syft_test.go
  adapters/v1/syft_to_domain.go
  adapters/v1/syft_to_domain_test.go
  adapters/v1/syft_utils.go
  adapters/v1/testdata/alpine-cve.format.json
  adapters/v1/testdata/alpine-cve.json
  adapters/v1/testdata/alpine-cvep.json
  adapters/v1/testdata/alpine-relevant-cve.format.json
  adapters/v1/testdata/alpine-sbom.format.json
  adapters/v1/testdata/alpine-sbom.json
  adapters/v1/testdata/hello-world-sbom.format.json
  adapters/v1/testdata/hello-world-sbom.json
  adapters/v1/testdata/listing.json
  adapters/v1/testdata/nginx-cve-small.json
  adapters/v1/testdata/nginx-cve.json
  adapters/v1/testdata/nginx-filtered-cve.format.json
  adapters/v1/testdata/nginx-filtered-cve.json
  adapters/v1/testdata/nginx-filtered-sbom.json
  adapters/v1/testdata/nginx-sbom.json
  adapters/v1/testdata/vulnerability-db_v5_2023-03-24T06_54_57Z_fab15e5405c096d82dfd.tar.gz
  build/Dockerfile
  controllers/http.go
  controllers/http_test.go
  core/domain/cve.go
  core/domain/sbom.go
  core/domain/scan.go
  core/services/scan.go
  core/services/scan_test.go
  go.mod
  go.sum
  internal/tools/tools.go
  repositories/apiserver.go
  repositories/apiserver_test.go
  repositories/memory_test.go
Labels: enhancement

#198 fix test data
  adapters/v1/domain_to_syft_test.go
  adapters/v1/grype_test.go
  adapters/v1/testdata/alpine-cve.json
  adapters/v1/testdata/hello-world-sbom.format.json
  adapters/v1/testdata/hello-world-sbom.json
  adapters/v1/testdata/listing.json
Labels: bug_fix

#200 Fix scan image multiple creds
  core/services/scan.go
  core/services/scan_test.go
Labels: Tests, Bug fix

#202 Fix serveraddress parsing
  core/services/scan.go
  core/services/scan_test.go
Labels: Bug fix

#203 Fix serveraddress parsing, log appropriate message in case of rate limiting by the configured backend
  adapters/v1/backend_utils.go
  core/services/scan.go
  core/services/scan_test.go
Labels: Bug fix

#204 fix tests
  adapters/v1/testdata/cve-body-with-exception.json
  adapters/v1/testdata/cve-body.json
Labels: release, Tests

#205 add back image size limits
  adapters/v1/domain_to_syft_test.go
  adapters/v1/syft.go
  adapters/v1/syft_test.go
  adapters/v1/testdata/alpine-sbom.format.json
  adapters/v1/testdata/alpine-sbom.json
  adapters/v1/testdata/hello-world-sbom.format.json
  adapters/v1/testdata/hello-world-sbom.json
  adapters/v1/testdata/stretch-slim-sbom.format.json
  controllers/http_test.go
  core/domain/scan.go
  core/services/scan_test.go
  go.mod
  go.sum
Labels: release
