Repository kubescape/kubevuln, pull requests merged in 2024-03, with the labels that each got.

#213 fix image load in registry scanning
  adapters/mockplatform.go
  adapters/v1/backend.go
  adapters/v1/syft.go
  adapters/v1/syft_test.go
  core/ports/providers.go
  core/services/scan.go
Labels: enhancement, release, bug_fix, Review effort [1-5]: 2

#215 add UT for scanTimeout
  adapters/v1/syft_test.go
Labels: enhancement, Tests, Review effort [1-5]: 2

#214 Update pr-merged.yaml
  .github/workflows/pr-merged.yaml
Labels: enhancement, Review effort [1-5]: 1

#216 bump storage
  go.mod
  go.sum
Labels: enhancement, release, Review effort [1-5]: 1

#217 bump actions/checkout to v4
  .github/workflows/scorecard.yml
Labels: enhancement, Review effort [1-5]: 1

#218 remove SBOMSummary creation
  go.mod
  go.sum
  repositories/apiserver.go
  repositories/apiserver_test.go
Labels: enhancement, Review effort [1-5]: 2

#220 Last chunk
  adapters/v1/backend_utils.go
  adapters/v1/backend_utils_test.go
  adapters/v1/testdata/report.json
Labels: enhancement, release, Tests, Review effort [1-5]: 4
