Repository kubescape/kubevuln, pull requests merged in 2024-04, with the labels that each got.

#222 Adding hotfix to syft version
  adapters/v1/syft.go
  go.mod
  go.sum
Labels: enhancement, release, bug_fix, Review effort [1-5]: 2

#221 fix ossf/scorecard
  .github/workflows/scorecard.yml
Labels: enhancement, Review effort [1-5]: 1

#224 Copy artifacts to filtered SBOMs
  core/domain/scan.go
  core/services/scan.go
  repositories/apiserver.go
  repositories/apiserver_test.go
Labels: enhancement, release, bug_fix, Review effort [1-5]: 3

#225 Check content is not nil
  core/services/scan.go
Labels: release, bug_fix
